# Generated by Django 3.0.3 on 2021-06-19 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_ordermodel_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='street',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='zip_code',
        ),
    ]
